/* CRIA TABELAS NECESSÁRIAS AO SISTEMA */

--TABELA LINHA
CREATE TABLE SITP.LINHA (
    IDLINHA NUMBER(9) NOT NULL,
    NUMERO NUMBER(4) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    TIPO VARCHAR(2) NOT NULL,
    ATIVA NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ID_LINHA PRIMARY KEY (IDLINHA)
);
CREATE SEQUENCE SITP.SEQ_LINHA START WITH 1 INCREMENT BY 1 CACHE 2 NOCYCLE;
COMMIT;

--TABELA ITINERÁRIO
CREATE TABLE SITP.ITINERARIO (
    IDITINERARIO NUMBER(9) NOT NULL,
    IDLINHA NUMBER(9) NOT NULL,
    ITINERARIO CLOB NOT NULL,
    RESUMO VARCHAR2(500) NOT NULL,
    SENTIDO VARCHAR(1) NOT NULL,
    PONTOINICIAL VARCHAR2(100) NOT NULL,
    PONTOFINAL VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ID_ITINERARIO PRIMARY KEY (IDITINERARIO),
    CONSTRAINT FK_ID_LINHA_2 FOREIGN KEY (IDLINHA) REFERENCES SITP.LINHA(IDLINHA)
);
CREATE SEQUENCE SITP.SEQ_ITINERARIO START WITH 1 INCREMENT BY 1 CACHE 2 NOCYCLE;
COMMIT;

--TABELA HORÁRIO
CREATE TABLE SITP.HORARIO (
    IDHORARIO NUMBER(9) NOT NULL,
    IDLINHA NUMBER(9) NOT NULL,
    INICIODIAUTIL VARCHAR2(5) NOT NULL,
    FIMDIAUTIL VARCHAR2(5) NOT NULL,
    INICIOSABADO VARCHAR2(5) NOT NULL,
    FIMSABADO VARCHAR2(5) NOT NULL,
    INICIODOMINGOEFERIADO VARCHAR2(5) NOT NULL,
    FIMDOMINGOEFERIADO VARCHAR2(5) NOT NULL,
    INTERVALODIAUTIL NUMBER(3) NOT NULL,
    INTERVALOSABADO NUMBER(3) NOT NULL,
    INTERVALODOMINGOEFERIADO NUMBER(3) NOT NULL,
    CONSTRAINT PK_ID_HORARIO PRIMARY KEY (IDHORARIO),
    CONSTRAINT FK_ID_LINHA_1 FOREIGN KEY (IDLINHA) REFERENCES SITP.LINHA(IDLINHA)
);
CREATE SEQUENCE SITP.SEQ_HORARIO START WITH 1 INCREMENT BY 1 CACHE 2 NOCYCLE;
COMMIT;
